[package]
name = "proc-macro-fsm1"
version = "0.2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["extra-traits", "full", "parsing"] }
quote = "1.0"
proc-macro2 = "1.0"
